# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDB_Master',
            fields=[
                ('Cust_ID', models.AutoField(db_column='Cust_ID', primary_key=True, serialize=False)),
                ('Cust_Name', models.CharField(db_column='Cust_name', max_length=200)),
                ('Tel_No', models.CharField(db_column='Tel_No', max_length=10, unique=True)),
                ('Email', models.CharField(db_column='Email', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDB_Master',
            fields=[
                ('Prod_ID', models.AutoField(db_column='Prod_ID', primary_key=True, serialize=False)),
                ('Prod_Name', models.CharField(db_column='Prod_Name', max_length=200, unique=True)),
                ('Real_Price_ToCompany', models.DecimalField(db_column='Real_Price_ToCompany', decimal_places=2, max_digits=10)),
                ('Marked_Price_OnProduct', models.DecimalField(db_column='Marked_Price_OnProduct', decimal_places=2, max_digits=10)),
                ('Selling_Price_ToCustomer', models.DecimalField(db_column='Selling_Price_ToCustomer', decimal_places=2, max_digits=10)),
                ('Items_In_Inventory', models.IntegerField(db_column='Items_In_Inventory')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDB_Master',
            fields=[
                ('Transaction_ID', models.AutoField(db_column='Transaction_ID', primary_key=True, serialize=False)),
                ('Cust_ID', models.IntegerField(db_column='Cust_ID')),
                ('Date_Of_Purchase', models.DateField(auto_now_add=True, db_column='Date_Of_Purchase')),
                ('Time_Of_Purchase', models.TimeField(auto_now_add=True, db_column='Time_Of_Purchase')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionSupportDB_Master',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('Transaction_ID', models.IntegerField(db_column='Transaction_ID')),
                ('Prod_ID', models.IntegerField(db_column='Prod_ID')),
                ('Real_Price_ToCompany', models.DecimalField(db_column='Real_Price_ToCompany', decimal_places=2, max_digits=10)),
                ('Selling_Price_ToCustomer', models.DecimalField(db_column='Selling_Price_ToCustomer', decimal_places=2, max_digits=10)),
                ('Quantity_Purchased', models.IntegerField(db_column='Quantity_Purchased', default=1)),
                ('Profit_Loss', models.DecimalField(db_column='Profit_Loss', decimal_places=2, max_digits=10)),
            ],
        ),
    ]
